title: "Bo Min Keum"
subtitle: "ICCRI, SFU" # We will use CSS to display this next to your name
url: "https://bomin-keum.github.io"
remote_theme: "mmistakes/minimal-mistakes"

# Top Navigation (These will appear next to your name)
masthead_links:
  - title: "About"
    url: "#about"
  - title: "Research"
    url: "#research"
  - title: "CV"
    url: "#cv"
  - title: "Contact"
    url: "#contact"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: false # We are hiding the sidebar for a cleaner top-nav look

collections:
  publications:
    output: true
    permalink: /:collection/:path/
