# Site Settings
url: "https://bomin-keum.github.io"
baseurl: ""
repository: "bomin-keum/bomin-keum.github.io"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Top Navigation Row (The "Subheadings")
masthead_links:
  - title: "About"
    url: "#about"
  - title: "Research"
    url: "#research"
  - title: "CV"
    url: "#cv"
  - title: "Contact"
    url: "#contact"

# Sidebar Profile
author:
  name: "Bomin Keum"
  bio: "PhD Student<br>International Cybercrime Research Institute, SFU"
  follow_button: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
